// Sample products data with categories
const PRODUCTS=[{id:1,name:'Wireless Earbuds Bluetooth 5.3',price:2999,category:'electronics',description:'Comfortable, long-lasting battery'},{id:2,name:'Fast Charging USB-C Cable 1m',price:699,category:'electronics',description:'Durable cable with fast charging'},{id:3,name:'Smart LED Desk Lamp',price:1499,category:'electronics',description:'Adjustable brightness, USB powered'},{id:4,name:'Premium Bed Sheets Set',price:1299,category:'home',description:'Soft, breathable cotton, fits all beds'},{id:5,name:'Kitchen Knife Set (6 pieces)',price:2499,category:'home',description:'Stainless steel blades, perfect for all'},{id:6,name:'Throw Pillow Cushion',price:799,category:'home',description:'Comfortable polyester fill, decorative'},{id:7,name:'Classic Cotton T-Shirt',price:499,category:'fashion',description:'Comfortable fit, available in multiple'},{id:8,name:'Denim Jeans (Slim Fit)',price:1899,category:'fashion',description:'Premium denim, perfect for everyday'},{id:9,name:'Running Shoes Lightweight',price:3499,category:'fashion',description:'Comfortable and durable for all runs'},{id:10,name:'Portable Phone Charger 20000mAh',price:1999,category:'electronics',description:'Fast charging, compact size'},{id:11,name:'Yoga Mat Non-Slip',price:899,category:'sports',description:'Thick padding, eco-friendly material'},{id:12,name:'Stainless Steel Water Bottle',price:599,category:'sports',description:'Keeps cool for 24 hours'}];
class AIRecommendationEngine{constructor(){this.viewedProducts=[];this.categoryInterests={}}trackProductView(e){this.viewedProducts.includes(e)||this.viewedProducts.push(e);const t=PRODUCTS.find(t=>t.id===e);t&&(this.categoryInterests[t.category]=(this.categoryInterests[t.category]||0)+1),localStorage.setItem('aiViewedProducts',JSON.stringify(this.viewedProducts)),localStorage.setItem('aiCategoryInterests',JSON.stringify(this.categoryInterests))}getRecommendations(e=4){const t=[];Object.entries(this.categoryInterests).sort((e,t)=>t[1]-e[1])[0]&&(t.push(...PRODUCTS.filter(e=>!this.viewedProducts.includes(e.id))));return t.push(...PRODUCTS.filter(e=>!t.includes(e)&&!this.viewedProducts.includes(e.id))),t.slice(0,e)}}
const aiEngine=new AIRecommendationEngine;
function loadAIData(){const e=localStorage.getItem('aiViewedProducts'),t=localStorage.getItem('aiCategoryInterests');e&&(aiEngine.viewedProducts=JSON.parse(e)),t&&(aiEngine.categoryInterests=JSON.parse(t))}- Updated top-header LOGIN link to point to register.html
- Connected Account icon to register.html for authentication
- Improved navigation flow between home, account, and registration
- Users can now register or login from header links
function setupSmartSearch(){const e=document.getElementById('searchInput'),t=document.getElementById('searchSuggestions');e.addEventListener('input',e=>{const r=e.target.value.toLowerCase();r.length<2?t.innerHTML='':t.innerHTML=PRODUCTS.filter(e=>e.name.toLowerCase().includes(r)||e.description.toLowerCase().includes(r)).slice(0,5).map(e=>`<div class="search-suggestion-item" onclick="aiEngine.trackProductView(${e.id})"><strong>${e.name}</strong><br><small>Rs. ${e.price}</small></div>`).join('')})}
function displayProducts(e=PRODUCTS,t='productsGrid'){document.getElementById(t).innerHTML=e.map(e=>`<div class="product-card" onclick="aiEngine.trackProductView(${e.id})"><div class="product-image-container">📦</div><div class="product-info"><div class="product-name">${e.name}</div><div class="product-price"><span class="price-current">Rs. ${e.price}</span><span class="discount">-15%</span></div><div class="product-rating">★★★★★ (234)</div><button class="add-to-cart-btn" onclick="event.stopPropagation(); addToCart(${e.id}, '${e.name}', ${e.price})">Add to Cart</button></div></div>`).join('')}
function displayRecommendations(){displayProducts(aiEngine.getRecommendations(4),'recommendedProducts')}
let cart=JSON.parse(localStorage.getItem('cart'))||[];
function addToCart(e,t,r){cart.push({id:e,name:t,price:r,quantity:1}),localStorage.setItem('cart',JSON.stringify(cart)),updateCartCount(),showNotification(t+' added to cart!')}
function removeFromCart(e){cart=cart.filter(t=>t.id!==e),localStorage.setItem('cart',JSON.stringify(cart)),updateCartCount(),displayCartItems()}
function updateCartCount(){document.getElementById('cartCount').textContent=cart.length}
function displayCartItems(){const e=document.getElementById('cartItems');e.innerHTML=0===cart.length?'<p style="text-align: center; padding: 20px;">Your cart is empty</p>':cart.map(e=>`<div class="cart-item"><div class="cart-item-image">🛍️</div><div class="cart-item-details"><div class="cart-item-name">${e.name}</div><div class="cart-item-price">Rs. ${e.price}</div><div class="cart-item-remove" onclick="removeFromCart(${e.id})">Remove</div></div></div>`).join('');document.getElementById('cartTotal').textContent=cart.reduce((e,t)=>e+t.price,0)}
function setupSmoothNavigation(){const e=document.getElementById('cartIcon'),t=document.getElementById('cartModal'),r=document.querySelector('.close-cart'),o=document.getElementById('accountIcon'),c=document.getElementById('accountModal'),a=document.querySelector('.close-modal');e.addEventListener('click',()=>{t.classList.add('active'),displayCartItems()}),r.addEventListener('click',()=>{t.classList.remove('active')}),t.addEventListener('click',e=>{e.target===t&&t.classList.remove('active')}),o.addEventListener('click',()=>{c.classList.add('active')}),a.addEventListener('click',()=>{c.classList.remove('active')}),c.addEventListener('click',e=>{e.target===c&&c.classList.remove('active')})}
function setupCategoryFiltering(){document.querySelectorAll('.category-item').forEach(e=>{e.addEventListener('click',t=>{t.preventDefault(),document.querySelectorAll('.category-item').forEach(e=>e.classList.remove('active')),e.classList.add('active');const r=e.dataset.category;'all'===r?displayProducts(PRODUCTS):displayProducts(PRODUCTS.filter(e=>e.category===r))})})}
function startFlashSaleTimer(){setInterval(()=>{const e=new Date;document.getElementById('hours').textContent=String(23-e.getHours()).padStart(2,'0'),document.getElementById('minutes').textContent=String(59-e.getMinutes()).padStart(2,'0'),document.getElementById('seconds').textContent=String(59-e.getSeconds()).padStart(2,'0')},1e3)}
function showNotification(e){const t=document.createElement('div');t.style.cssText='position: fixed; top: 20px; right: 20px; background: #27AE60; color: white; padding: 15px 20px; border-radius: 4px; z-index: 2000; animation: slideUp 0.3s ease;',t.textContent=e,document.body.appendChild(t),setTimeout(()=>t.remove(),3e3)}
window.addEventListener('DOMContentLoaded',()=>{loadAIData(),displayProducts(),displayRecommendations(),setupSmartSearch(),setupSmoothNavigation(),setupCategoryFiltering(),startFlashSaleTimer(),updateCartCount()}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener('click',t=>{const r=e.getAttribute('href');'#'!==r&&document.querySelector(r)&&(t.preventDefault(),document.querySelector(r).scrollIntoView({behavior:'smooth'}))})}),o.addEventListener('click',()=>window.location='register.html');



